name: AVR Release Build

on:
  push:
    tags:
      - 'v*'  # Trigger on new version tags (e.g., v1.0.0)

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install AVR toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y avr-libc avr-gcc gcc-avr binutils-avr

    - name: Configure CMake
      run: cmake -B build -S .

    - name: Build Hex File
      run: cmake --build build --target hex

    - name: Create Release and Upload Hex
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/WattsApp.hex
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
